### ISSUE TITLE
how to use this code in diffusers?

### ISSUE THREAD

**Issue by howardgriffin** [ChenyangSi/FreeU#12]

**Comment by justindujardin** [comment]
https://github.com/huggingface/diffusers/pull/5164#issuecomment-1732638706

**Comment by lyn-rgb** [comment]
https://github.com/lyn-rgb/FreeU_Diffusers

**Comment by haofanwang** [comment]
Awesome!

**Comment by putuoka** [comment]
> https://github.com/lyn-rgb/FreeU_Diffusers

that's really quick u have to be good at coding

**Comment by ChenyangSi** [comment]
> https://github.com/lyn-rgb/FreeU_Diffusers

**Comment by MythicalChu** [comment]
For AMD cards and others that can't run it on the gpu:
https://github.com/MythicalChu/FreeU_Diffusers_CPU
