### ISSUE TITLE
What are the parameters for 1.5 or XL?

### ISSUE THREAD

**Issue by ninjasaid2k** [ChenyangSi/FreeU#4]

**Comment by ChenyangSi** [comment]
https://wandb.ai/nasirk24/UNET-FreeU-SDXL/reports/FreeU-SDXL-Optimal-Parameters--Vmlldzo1NDg4NTUw?accessToken=6745kr9rjd6e9yjevkr9bpd2lm6dpn6j00428gz5l60jrhl3gj4gubrz4aepupda
